export enum ActionTypeStates {
    INPROGRESS = "_INPROGRESS",
    SUCCESS = "_SUCCESS",
    FAIL = "_FAIL"
}

enum ActionTypeKeys {
    IMAGE_UPLOAD_INPROGRESS = "IMAGE_UPLOAD_INPROGRESS",
    IMAGE_UPLOAD_SUCCESS = "IMAGE_UPLOAD_SUCCESS",
    IMAGE_UPLOAD_FAIL = "IMAGE_UPLOAD_FAIL",

    ADD_IMAGES_TO_EVENT_INPROGRESS = "ADD_IMAGES_TO_EVENT_INPROGRESS",
    ADD_IMAGES_TO_EVENT_SUCCESS = "ADD_IMAGES_TO_EVENT_SUCCESS",
    ADD_IMAGES_TO_EVENT_FAIL = "ADD_IMAGES_TO_EVENT_FAIL",

    CREATE_EVENT_INPROGRESS = "CREATE_EVENT_INPROGRESS",
    CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS",
    CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL"
}

export default ActionTypeKeys